"""
Phase 2 Models: LLM-Powered Features

Models for adaptive learning paths and LLM-graded assessments.
"""

from sqlalchemy import Column, String, Text, Integer, Numeric, Boolean, DateTime, ForeignKey, Enum as SQLEnum, CheckConstraint, Index
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
import enum
import datetime

from app.models.base import Base


class AdaptivePathStatus(str, enum.Enum):
    """Adaptive path lifecycle status"""
    ACTIVE = "active"
    EXPIRED = "expired"
    SUPERSEDED = "superseded"


class AdaptivePath(Base):
    """
    Personalized learning recommendations generated by Claude Sonnet 4.5.

    Stores generated adaptive paths with 24-hour validity period.
    """
    __tablename__ = "adaptive_paths"

    # Primary Key
    path_id = Column(UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid())

    # Foreign Keys
    student_id = Column(UUID(as_uuid=True), ForeignKey("students.student_id", ondelete="CASCADE"), nullable=False, index=True)

    # Metadata
    generated_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
    expires_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now() + datetime.timedelta(hours=24))

    # Recommendations (JSONB)
    recommendations_json = Column(JSONB, nullable=False)
    # Structure: [
    #   {
    #     "chapter_id": "04-rag",
    #     "section_id": "embeddings-review",
    #     "priority": 1,
    #     "reason": "Your quiz scores show weak understanding...",
    #     "estimated_impact": "high",
    #     "estimated_time_minutes": 30
    #   }
    # ]

    reasoning = Column(Text, nullable=False)

    # Cost Tracking
    tokens_input = Column(Integer, nullable=False)
    tokens_output = Column(Integer, nullable=False)
    cost_usd = Column(Numeric(10, 6), nullable=False)

    # Status
    status = Column(
        String(20),
        nullable=False,
        default=AdaptivePathStatus.ACTIVE
    )

    followed_at = Column(DateTime(timezone=True), nullable=True)
    completed_at = Column(DateTime(timezone=True), nullable=True)

    # Indexes
    __table_args__ = (
        Index("idx_adaptive_paths_student_id", "student_id"),
        Index("idx_adaptive_paths_generated_at", "generated_at"),
        Index("idx_adaptive_paths_status", "status"),
        Index("idx_adaptive_paths_expires_at", "expires_at"),
        # Composite index for cache lookups
        Index("idx_adaptive_paths_student_active", "student_id", "status", "expires_at"),
        # Validation constraints
        CheckConstraint("status IN ('active', 'expired', 'superseded')", name="check_status_values"),
        CheckConstraint("expires_at > generated_at", name="valid_expiration"),
    )


class AssessmentSubmissionStatus(str, enum.Enum):
    """Assessment grading status"""
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"


class AssessmentSubmission(Base):
    """
    Student's written answer to an open-ended assessment question.

    Stores answer text with 50-5000 character validation.
    """
    __tablename__ = "assessment_submissions"

    # Primary Key
    submission_id = Column(UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid())

    # Foreign Keys
    student_id = Column(UUID(as_uuid=True), ForeignKey("students.student_id", ondelete="CASCADE"), nullable=False, index=True)
    question_id = Column(String(50), nullable=False, index=True)
    previous_submission_id = Column(UUID(as_uuid=True), ForeignKey("assessment_submissions.submission_id"), nullable=True)

    # Submission Data
    answer_text = Column(Text, nullable=False)
    submitted_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    # Grading Status
    grading_status = Column(
        String(20),
        nullable=False,
        default=AssessmentSubmissionStatus.PENDING
    )
    grading_started_at = Column(DateTime(timezone=True), nullable=True)
    grading_completed_at = Column(DateTime(timezone=True), nullable=True)

    # Retry Tracking
    attempt_number = Column(Integer, nullable=False, default=1)

    # Error Handling
    error_message = Column(Text, nullable=True)

    # Indexes
    __table_args__ = (
        Index("idx_submissions_student_id", "student_id"),
        Index("idx_submissions_question_id", "question_id"),
        Index("idx_submissions_status", "grading_status"),
        Index("idx_submissions_submitted_at", "submitted_at"),
        # Composite index for student submission history
        Index("idx_submissions_student_question", "student_id", "question_id", "submitted_at"),
        # Validation constraints
        CheckConstraint("LENGTH(answer_text) BETWEEN 50 AND 5000", name="check_answer_length"),
        CheckConstraint("grading_status IN ('pending', 'processing', 'completed', 'failed')", name="check_grading_status"),
        CheckConstraint("attempt_number BETWEEN 1 AND 3", name="check_attempt_range"),
        CheckConstraint(
            "grading_completed_at IS NULL OR grading_started_at IS NULL OR grading_completed_at >= grading_started_at",
            name="valid_grading_timeline"
        ),
    )


class AssessmentFeedback(Base):
    """
    LLM-generated grading feedback for assessment submissions.

    Stores detailed feedback with quality scores, strengths, and improvements.
    """
    __tablename__ = "assessment_feedback"

    # Primary Key
    feedback_id = Column(UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid())

    # Foreign Keys
    submission_id = Column(UUID(as_uuid=True), ForeignKey("assessment_submissions.submission_id", ondelete="CASCADE"), nullable=False, unique=True)
    human_reviewer_id = Column(UUID(as_uuid=True), ForeignKey("students.student_id"), nullable=True)

    # Grading Results
    quality_score = Column(Numeric(3, 1), nullable=False)

    # Structured Feedback (JSONB)
    strengths_json = Column(JSONB, nullable=False)
    # Structure: [
    #   "Strong explanation of cost tradeoffs",
    #   "Good use of concrete examples"
    # ]

    improvements_json = Column(JSONB, nullable=False)
    # Structure: [
    #   "Missing discussion of data privacy considerations",
    #   "Could expand on computational costs"
    # ]

    detailed_feedback = Column(Text, nullable=False)

    # Metadata
    generated_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    # Cost Tracking
    tokens_input = Column(Integer, nullable=False)
    tokens_output = Column(Integer, nullable=False)
    cost_usd = Column(Numeric(10, 6), nullable=False)

    # Quality Assurance
    is_off_topic = Column(Boolean, nullable=False, default=False, server_default="false")
    human_reviewed = Column(Boolean, nullable=False, default=False, server_default="false")
    human_review_notes = Column(Text, nullable=True)

    # Indexes
    __table_args__ = (
        Index("idx_feedback_submission_id", "submission_id"),
        Index("idx_feedback_generated_at", "generated_at"),
        Index("idx_feedback_score", "quality_score"),
        # Index for quality monitoring
        Index("idx_feedback_unreviewed", "human_reviewed", "generated_at"),
        # Validation constraints
        CheckConstraint("quality_score BETWEEN 0 AND 10", name="check_quality_score_range"),
        CheckConstraint("jsonb_array_length(strengths_json) BETWEEN 1 AND 5", name="valid_strengths"),
        CheckConstraint("jsonb_array_length(improvements_json) BETWEEN 1 AND 5", name="valid_improvements"),
    )
