"""Initial schema - Phase 1 models

Revision ID: f951f945330e
Revises: 
Create Date: 2026-01-24 19:51:44.809267+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f951f945330e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), server_default='free', nullable=False),
    sa.Column('subscription_expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('last_active_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_active_email', 'users', ['is_active', 'email'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_last_active', 'users', ['last_active_at'], unique=False)
    op.create_index('idx_users_subscription_tier', 'users', ['subscription_tier'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_last_active_at'), 'users', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_users_subscription_tier'), 'users', ['subscription_tier'], unique=False)
    op.create_table('chapter_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_section_id', sa.String(length=100), nullable=True),
    sa.Column('completion_percentage', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chapter_progress_chapter_id', 'chapter_progress', ['chapter_id'], unique=False)
    op.create_index('idx_chapter_progress_completed', 'chapter_progress', ['is_completed'], unique=False)
    op.create_index('idx_chapter_progress_user_chapter', 'chapter_progress', ['user_id', 'chapter_id'], unique=True)
    op.create_index('idx_chapter_progress_user_id', 'chapter_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_chapter_progress_chapter_id'), 'chapter_progress', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_chapter_progress_user_id'), 'chapter_progress', ['user_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.String(length=100), nullable=False),
    sa.Column('chapter_id', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('score_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quiz_attempts_chapter_id', 'quiz_attempts', ['chapter_id'], unique=False)
    op.create_index('idx_quiz_attempts_completed', 'quiz_attempts', ['completed_at'], unique=False)
    op.create_index('idx_quiz_attempts_passed', 'quiz_attempts', ['passed'], unique=False)
    op.create_index('idx_quiz_attempts_quiz_id', 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index('idx_quiz_attempts_user_id', 'quiz_attempts', ['user_id'], unique=False)
    op.create_index('idx_quiz_attempts_user_quiz', 'quiz_attempts', ['user_id', 'quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_chapter_id'), 'quiz_attempts', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('interaction_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_chapter_id', sa.String(length=50), nullable=True),
    sa.Column('last_section_id', sa.String(length=100), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('platform', sa.String(length=20), server_default='chatgpt', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_platform', 'sessions', ['platform'], unique=False)
    op.create_index('idx_sessions_started_at', 'sessions', ['started_at'], unique=False)
    op.create_index('idx_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_index('idx_sessions_user_started', 'sessions', ['user_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_sessions_started_at'), 'sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('streaks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_active_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_activity_date', sa.DATE(), nullable=True),
    sa.Column('streak_freeze_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_streaks_current', 'streaks', ['current_streak'], unique=False)
    op.create_index('idx_streaks_last_activity', 'streaks', ['last_activity_date'], unique=False)
    op.create_index('idx_streaks_user_id', 'streaks', ['user_id'], unique=False)
    op.create_index(op.f('ix_streaks_last_activity_date'), 'streaks', ['last_activity_date'], unique=False)
    op.create_index(op.f('ix_streaks_user_id'), 'streaks', ['user_id'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.String(length=20), server_default='free', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('price_cents', sa.DECIMAL(precision=10, scale=0), server_default='0', nullable=False),
    sa.Column('billing_period', sa.String(length=20), server_default='monthly', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subscriptions_expires_at', 'subscriptions', ['expires_at'], unique=False)
    op.create_index('idx_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_index('idx_subscriptions_tier', 'subscriptions', ['tier'], unique=False)
    op.create_index('idx_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index('idx_subscriptions_user_id', table_name='subscriptions')
    op.drop_index('idx_subscriptions_tier', table_name='subscriptions')
    op.drop_index('idx_subscriptions_status', table_name='subscriptions')
    op.drop_index('idx_subscriptions_expires_at', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_streaks_user_id'), table_name='streaks')
    op.drop_index(op.f('ix_streaks_last_activity_date'), table_name='streaks')
    op.drop_index('idx_streaks_user_id', table_name='streaks')
    op.drop_index('idx_streaks_last_activity', table_name='streaks')
    op.drop_index('idx_streaks_current', table_name='streaks')
    op.drop_table('streaks')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_started_at'), table_name='sessions')
    op.drop_index('idx_sessions_user_started', table_name='sessions')
    op.drop_index('idx_sessions_user_id', table_name='sessions')
    op.drop_index('idx_sessions_started_at', table_name='sessions')
    op.drop_index('idx_sessions_platform', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_quiz_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_chapter_id'), table_name='quiz_attempts')
    op.drop_index('idx_quiz_attempts_user_quiz', table_name='quiz_attempts')
    op.drop_index('idx_quiz_attempts_user_id', table_name='quiz_attempts')
    op.drop_index('idx_quiz_attempts_quiz_id', table_name='quiz_attempts')
    op.drop_index('idx_quiz_attempts_passed', table_name='quiz_attempts')
    op.drop_index('idx_quiz_attempts_completed', table_name='quiz_attempts')
    op.drop_index('idx_quiz_attempts_chapter_id', table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_chapter_progress_user_id'), table_name='chapter_progress')
    op.drop_index(op.f('ix_chapter_progress_chapter_id'), table_name='chapter_progress')
    op.drop_index('idx_chapter_progress_user_id', table_name='chapter_progress')
    op.drop_index('idx_chapter_progress_user_chapter', table_name='chapter_progress')
    op.drop_index('idx_chapter_progress_completed', table_name='chapter_progress')
    op.drop_index('idx_chapter_progress_chapter_id', table_name='chapter_progress')
    op.drop_table('chapter_progress')
    op.drop_index(op.f('ix_users_subscription_tier'), table_name='users')
    op.drop_index(op.f('ix_users_last_active_at'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_subscription_tier', table_name='users')
    op.drop_index('idx_users_last_active', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_active_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
